### ISSUE TITLE
Can we give multiple prompts at once?

### ISSUE THREAD

**Issue by TejaswiniiB** [entrpn/serving-diffusion#6]
Hi,

Can prompts list in request json contain more than 1 prompts as shown below and get respective response images in single api call? Even if I give multiple prompts, I am getting 4 images related to 1st prompt only in the response, hence I got this doubt.

`prompts_list = [{"prompt": "elephant talking to spiderman"}, {"prompt": "sparrow sitting on a tiger"}] `

**Comment by entrpn** [comment]
@TejaswiniiB I wrote the code so that you can only make 1 prompt per request, even if the api takes multiple prompts. This is because the Vertex AI endpoint has a max request time of 60 seconds and didn't want to max it out. However, I realize that this can also run outside of Vertex, so I'll make the change this week.

**Comment by entrpn** [comment]
@TejaswiniiB this has been implemented now. The request signature has changed, please look at the README inside the stable-diffusion folder.
